# Week 4 Bank Data 
Chris Richards, Regis University  
Data Collection and Preparation, Spring 2019  
  
This project takes the Bank Marketing data set from the UCI ML Archive and conducts some clean up of the data and column headers.  
Several headers contain underscores and periods which will be removed, as well as series values with similar issues.  In many columns missing data is labeled as "unknown".  In these cases, the series data types are "category" and "unknown" as a value is appropriate.  These values will remain as is.  

One column, pdays, records number of days and is an integer data type.  The original researchers coded missing data as 999.  This is problematic for performing calculations and will be replaced with NaN.

In [419]:
import pandas as pd, numpy as np

In [420]:
#Can't seem to access a datafile in the same directory as the notebook.
# Using a magic command to change the working directory to the current dir
%cd "C:\Users\cr117\Documents\Regis\Data_Collection\Week4\"

C:\Users\cr117\Documents\Regis\Data_Collection\Week4


In [421]:
df = pd.read_csv("bank-additional.csv", delimiter=';')

In [422]:
df.head()

age          job  marital          education default  housing     loan  \
0   30  blue-collar  married           basic.9y      no      yes       no   
1   39     services   single        high.school      no       no       no   
2   25     services  married        high.school      no      yes       no   
3   38     services  married           basic.9y      no  unknown  unknown   
4   47       admin.  married  university.degree      no      yes       no   

     contact month day_of_week ...  campaign  pdays  previous     poutcome  \
0   cellular   may         fri ...         2    999         0  nonexistent   
1  telephone   may         fri ...         4    999         0  nonexistent   
2  telephone   jun         wed ...         1    999         0  nonexistent   
3  telephone   jun         fri ...         3    999         0  nonexistent   
4   cellular   nov         mon ...         1    999         0  nonexistent   

  emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0         -1.8          92.893          -46.2      1.313       5099.1  no  
1          1.1          93.994          -36.4      4.855       5191.0  no  
2          1.4          94.465          -41.8      4.962       5228.1  no  
3          1.4          94.465          -41.8      4.959       5228.1  no  
4         -0.1          93.200          -42.0      4.191       5195.8  no  

[5 rows x 21 columns]

In [423]:
df.shape

(4119, 21)

In [424]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4119 entries, 0 to 4118
Data columns (total 21 columns):
age               4119 non-null int64
job               4119 non-null object
marital           4119 non-null object
education         4119 non-null object
default           4119 non-null object
housing           4119 non-null object
loan              4119 non-null object
contact           4119 non-null object
month             4119 non-null object
day_of_week       4119 non-null object
duration          4119 non-null int64
campaign          4119 non-null int64
pdays             4119 non-null int64
previous          4119 non-null int64
poutcome          4119 non-null object
emp.var.rate      4119 non-null float64
cons.price.idx    4119 non-null float64
cons.conf.idx     4119 non-null float64
euribor3m         4119 non-null float64
nr.employed       4119 non-null float64
y                 4119 non-null object
dtypes: float64(5), int64(5), object(11)
memory usage: 675.9+ KB


In [425]:
# make copy
dfc = df.copy()

In [426]:
dfc.head()

age          job  marital          education default  housing     loan  \
0   30  blue-collar  married           basic.9y      no      yes       no   
1   39     services   single        high.school      no       no       no   
2   25     services  married        high.school      no      yes       no   
3   38     services  married           basic.9y      no  unknown  unknown   
4   47       admin.  married  university.degree      no      yes       no   

     contact month day_of_week ...  campaign  pdays  previous     poutcome  \
0   cellular   may         fri ...         2    999         0  nonexistent   
1  telephone   may         fri ...         4    999         0  nonexistent   
2  telephone   jun         wed ...         1    999         0  nonexistent   
3  telephone   jun         fri ...         3    999         0  nonexistent   
4   cellular   nov         mon ...         1    999         0  nonexistent   

  emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0         -1.8          92.893          -46.2      1.313       5099.1  no  
1          1.1          93.994          -36.4      4.855       5191.0  no  
2          1.4          94.465          -41.8      4.962       5228.1  no  
3          1.4          94.465          -41.8      4.959       5228.1  no  
4         -0.1          93.200          -42.0      4.191       5195.8  no  

[5 rows x 21 columns]

In [427]:
dfc.tail()

age         job  marital    education default housing loan    contact  \
4114   30      admin.  married     basic.6y      no     yes  yes   cellular   
4115   39      admin.  married  high.school      no     yes   no  telephone   
4116   27     student   single  high.school      no      no   no   cellular   
4117   58      admin.  married  high.school      no      no   no   cellular   
4118   34  management   single  high.school      no     yes   no   cellular   

     month day_of_week ...  campaign  pdays  previous     poutcome  \
4114   jul         thu ...         1    999         0  nonexistent   
4115   jul         fri ...         1    999         0  nonexistent   
4116   may         mon ...         2    999         1      failure   
4117   aug         fri ...         1    999         0  nonexistent   
4118   nov         wed ...         1    999         0  nonexistent   

     emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
4114          1.4          93.918          -42.7      4.958       5228.1  no  
4115          1.4          93.918          -42.7      4.959       5228.1  no  
4116         -1.8          92.893          -46.2      1.354       5099.1  no  
4117          1.4          93.444          -36.1      4.966       5228.1  no  
4118         -0.1          93.200          -42.0      4.120       5195.8  no  

[5 rows x 21 columns]

In [428]:
dfc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4119 entries, 0 to 4118
Data columns (total 21 columns):
age               4119 non-null int64
job               4119 non-null object
marital           4119 non-null object
education         4119 non-null object
default           4119 non-null object
housing           4119 non-null object
loan              4119 non-null object
contact           4119 non-null object
month             4119 non-null object
day_of_week       4119 non-null object
duration          4119 non-null int64
campaign          4119 non-null int64
pdays             4119 non-null int64
previous          4119 non-null int64
poutcome          4119 non-null object
emp.var.rate      4119 non-null float64
cons.price.idx    4119 non-null float64
cons.conf.idx     4119 non-null float64
euribor3m         4119 non-null float64
nr.employed       4119 non-null float64
y                 4119 non-null object
dtypes: float64(5), int64(5), object(11)
memory usage: 675.9+ KB


##### Cleaning up punctuation in column headers.  
Some of the column names have underscores or periods.  I'll replace those with a space.

In [429]:
# remove periods from series 'job' and 'education'
dfc[['job', 'education']] = dfc[['job', 'education']].replace("\.", " ", regex=True)


In [430]:
dfc['education'].head(10)

0               basic 9y
1            high school
2            high school
3               basic 9y
4      university degree
5      university degree
6      university degree
7      university degree
8    professional course
9               basic 9y
Name: education, dtype: object

##### Change selected series to "category" type

In [431]:
cols = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'day_of_week', 'poutcome', 'y']
for col in cols:  
    dfc[col] = dfc[col].astype('category')

In [432]:
# check the conversion
dfc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4119 entries, 0 to 4118
Data columns (total 21 columns):
age               4119 non-null int64
job               4119 non-null category
marital           4119 non-null category
education         4119 non-null category
default           4119 non-null category
housing           4119 non-null category
loan              4119 non-null category
contact           4119 non-null category
month             4119 non-null category
day_of_week       4119 non-null category
duration          4119 non-null int64
campaign          4119 non-null int64
pdays             4119 non-null int64
previous          4119 non-null int64
poutcome          4119 non-null category
emp.var.rate      4119 non-null float64
cons.price.idx    4119 non-null float64
cons.conf.idx     4119 non-null float64
euribor3m         4119 non-null float64
nr.employed       4119 non-null float64
y                 4119 non-null category
dtypes: category(11), float64(5), int64(5)
memory us

##### Replace "999" pdays series
According to the data definition document, "999" is used in the "pdays" series to indicate that a client was not previously contacted.  The "pdays" series records the number of days since the client's last contact.  Using a numeric value of 999 is misleading.  This will cause issues with the accuracy of any numeric calculations performed on this series.  I'll convert the "999"s to NaN to prevent them from interfering.

In [433]:
# Check number of 999s in pdays
# Looking at the data file it seems there's a large number of 999 values.
nines = pd.value_counts(dfc['pdays'])
nines

999    3959
3        52
6        42
4        14
7        10
10        8
12        5
5         4
2         4
9         3
1         3
13        2
18        2
16        2
15        2
0         2
14        1
19        1
21        1
17        1
11        1
Name: pdays, dtype: int64

In [434]:
dfc['pdays'].replace(999, np.NaN, inplace=True)
dfc["pdays"].tail(5)

4114   NaN
4115   NaN
4116   NaN
4117   NaN
4118   NaN
Name: pdays, dtype: float64

Checking the conversion it appears that the values have been converted to floats by design  
Next, I'll check the count of values in the series.

In [435]:
nines = pd.value_counts(dfc['pdays'])
nines

3.0     52
6.0     42
4.0     14
7.0     10
10.0     8
12.0     5
5.0      4
2.0      4
1.0      3
9.0      3
18.0     2
15.0     2
0.0      2
16.0     2
13.0     2
17.0     1
11.0     1
14.0     1
19.0     1
21.0     1
Name: pdays, dtype: int64

No 999s are found but as an extra check, I'll count the NaNs.  

This should return 3959 if correct.  That value was shown as the result of counting the number of 999s in the pdays series. 

In [436]:
dfc['pdays'].isnull().sum()

3959

##### Convert month series 
In the month series, month names and abbreviations are used.  I'll convert them to the month's corresponding numbers.

##### Count the month values used

In [437]:
dfc['month'].unique()

[may, jun, nov, sep, jul, aug, mar, oct, apr, dec]
Categories (10, object): [may, jun, nov, sep, ..., mar, oct, apr, dec]

##### Create dictionary for month number

In [438]:
m = {
    "jan": '1', 
    "feb": '2', 
    "mar": '3',
    "apr": '4', 
    "may": '5', 
    "jun": '6', 
    "jul": '7', 
    "aug": '8', 
    "sep": '9', 
    "oct": '10', 
    "nov": '11', 
    "dec": '12', 
}

In [439]:
dfc['month'].replace(m, inplace=True)
dfc['month'].head(10)

0     5
1     5
2     6
3     6
4    11
5     9
6     9
7    11
8    11
9     5
Name: month, dtype: object

##### Count the unique values in the month series.

In [440]:
dfc['month'].unique()

array(['5', '6', '11', '9', '7', '8', '3', '10', '4', '12'], dtype=object)

#### Rename columns
Some of the column headers in this data set are unclear.  I'll rename them to something more descriptive.  

In [441]:
dfc.rename(columns={'job': 'job type', 'marital': 'marital status', 
                    'housing': 'housing loan', 'loan': 'personl loan', 
                    'contact': 'contact type', 'month': 'month of last contact',                      
                    'day_of_week': 'day of last contact', 'duration': 'duration of last contact',
                    'campaign': 'number of contacts', 'pdays': 'number of days from last campaign', 
                    'previous': 'number of previous contacts', 'poutcome': 'previous outcome',  
                    'emp.var.rate': 'employment variation rate', 
                    'cons.price.idx':'consumer price index', 'cons.conf.idx':'consumer confidence index', 
                    'euribor3m': 'euribor 3 month rate', 'nr.employed':"number of employees",
                    "y":"subscribed"}, inplace=True) 

In [442]:
dfc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4119 entries, 0 to 4118
Data columns (total 21 columns):
age                                  4119 non-null int64
job type                             4119 non-null category
marital status                       4119 non-null category
education                            4119 non-null category
default                              4119 non-null category
housing loan                         4119 non-null category
personl loan                         4119 non-null category
contact type                         4119 non-null category
month of last contact                4119 non-null object
day of last contact                  4119 non-null category
duration of last contact             4119 non-null int64
number of contacts                   4119 non-null int64
number of days from last campaign    160 non-null float64
number of previous contacts          4119 non-null int64
previous outcome                     4119 non-null category
employmen

In [443]:
dfc.head(10)

age      job type marital status            education  default  \
0   30   blue-collar        married             basic 9y       no   
1   39      services         single          high school       no   
2   25      services        married          high school       no   
3   38      services        married             basic 9y       no   
4   47        admin         married    university degree       no   
5   32      services         single    university degree       no   
6   32        admin          single    university degree       no   
7   41  entrepreneur        married    university degree  unknown   
8   31      services       divorced  professional course       no   
9   35   blue-collar        married             basic 9y  unknown   

  housing loan personl loan contact type month of last contact  \
0          yes           no     cellular                     5   
1           no           no    telephone                     5   
2          yes           no    telephone                     6   
3      unknown      unknown    telephone                     6   
4          yes           no     cellular                    11   
5           no           no     cellular                     9   
6          yes           no     cellular                     9   
7          yes           no     cellular                    11   
8           no           no     cellular                    11   
9           no           no    telephone                     5   

  day of last contact     ...      number of contacts  \
0                 fri     ...                       2   
1                 fri     ...                       4   
2                 wed     ...                       1   
3                 fri     ...                       3   
4                 mon     ...                       1   
5                 thu     ...                       3   
6                 mon     ...                       4   
7                 mon     ...                       2   
8                 tue     ...                       1   
9                 thu     ...                       1   

   number of days from last campaign  number of previous contacts  \
0                                NaN                            0   
1                                NaN                            0   
2                                NaN                            0   
3                                NaN                            0   
4                                NaN                            0   
5                                NaN                            2   
6                                NaN                            0   
7                                NaN                            0   
8                                NaN                            1   
9                                NaN                            0   

   previous outcome employment variation rate  consumer price index  \
0       nonexistent                      -1.8                92.893   
1       nonexistent                       1.1                93.994   
2       nonexistent                       1.4                94.465   
3       nonexistent                       1.4                94.465   
4       nonexistent                      -0.1                93.200   
5           failure                      -1.1                94.199   
6       nonexistent                      -1.1                94.199   
7       nonexistent                      -0.1                93.200   
8           failure                      -0.1                93.200   
9       nonexistent                       1.1                93.994   

   consumer confidence index  euribor 3 month rate  number of employees  \
0                      -46.2                 1.313               5099.1   
1                      -36.4                 4.855               5191.0   
2                      -41.8                 4.962               5228.1   
3                      -41.8                 4

In [444]:
dfc.tail(10)

age    job type marital status            education  default  \
4109   63     retired        married          high school       no   
4110   53   housemaid       divorced             basic 6y  unknown   
4111   30  technician        married    university degree       no   
4112   31  technician         single  professional course       no   
4113   31      admin          single    university degree       no   
4114   30      admin         married             basic 6y       no   
4115   39      admin         married          high school       no   
4116   27     student         single          high school       no   
4117   58      admin         married          high school       no   
4118   34  management         single          high school       no   

     housing loan personl loan contact type month of last contact  \
4109           no           no     cellular                    10   
4110      unknown      unknown    telephone                     5   
4111           no          yes     cellular                     6   
4112          yes           no     cellular                    11   
4113          yes           no     cellular                    11   
4114          yes          yes     cellular                     7   
4115          yes           no    telephone                     7   
4116           no           no     cellular                     5   
4117           no           no     cellular                     8   
4118          yes           no     cellular                    11   

     day of last contact     ...      number of contacts  \
4109                 wed     ...                       1   
4110                 fri     ...                       2   
4111                 fri     ...                       1   
4112                 thu     ...                       1   
4113                 thu     ...                       1   
4114                 thu     ...                       1   
4115                 fri     ...                       1   
4116                 mon     ...                       2   
4117                 fri     ...                       1   
4118                 wed     ...                       1   

      number of days from last campaign  number of previous contacts  \
4109                                NaN                            0   
4110                                NaN                            0   
4111                                NaN                            1   
4112                                NaN                            0   
4113                                NaN                            0   
4114                                NaN                            0   
4115                                NaN                            0   
4116                                NaN                            1   
4117                                NaN                            0   
4118                                NaN                            0   

      previous outcome employment variation rate  consumer price index  \
4109       nonexistent                      -3.4                92.431   
4110       nonexistent                       1.1                93.994   
4111           failure                      -1.7                94.055   
4112       nonexistent                      -0.1                93.200   
4113       nonexistent                      -0.1                93.200   
4114       nonexistent                       1.4                93.918   
4115       nonexistent                       1.4                93.918   
4116           failure                      -1.8                92.893   
4117       nonexistent                       1.4                93.444   
4118       nonexistent                      -0.1                93.200   

      consumer confidence index  euribor 3 month rate  number of employees  \
4109                      -26.9                 0.740               5017.5   
4110                      -36.4                 4.